export const teamList = [
    {
        name: "PROJECT DIRCTOR",
        members: [
            {
                nameJa: "真田将太朗",
                nameEn: "SHOTARO SANADA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                nameJa: "石津悠人",
                nameEn: "YUTO ISHIZU",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "中田裕紀",
                nameEn: "YUKI NAKATA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                nameJa: "南田桂吾",
                nameEn: "KEIGO MINAMIDA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "暦本研究室",
            },
        ],
    },
    {
        name: "PROJECT MANAGER",
        members: [
            {
                nameJa: "仲村友杜",
                nameEn: "YUTO NAKAMURA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "暦本研究室",
            },
            {
                nameJa: "星杏優菜",
                nameEn: "AYUNA HOSHI",
                affiliationJa: "フェリス女学院大学大学院 音楽研究科",
                grade: "修士2年",
                lab: "中西研究室",
            },
            {
                nameJa: "莫子敏",
                nameEn: "ZIMIN MO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "藤本研究室",
            },
        ],
    },
    {
        name: "BRANDING",
        members: [
            {
                nameJa: "横井総太朗",
                nameEn: "SOTARO YOKOI",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "宮道彩乃",
                nameEn: "AYANO MIYAMICHI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "岡田・小島研究室",
            },
        ],
    },
    {
        name: "ACCOUNTANT",
        members: [
            {
                nameJa: "友利未夢",
                nameEn: "MIYU TOMORI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "山内研究室",
            },
            {
                nameJa: "牛島百合子",
                nameEn: "YURIKO USHIJIMA",
                affiliationJa: "東京大学大学院 情報学環教育部",
                grade: "教育部 1年",
                lab: "渡邉研究室",
            },
        ],
    },
    {
        name: "DESIGN",
        members: [
            {
                nameJa: "李伊婧",
                nameEn: "ISEI LI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "李婧",
                nameEn: "JING LI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "渡邊研究室",
            },
            {
                nameJa: "余楚韵",
                nameEn: "CHUYUN YU",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "渡邊研究室",
            },
            {
                nameJa: "李嘉懿",
                nameEn: "ANRY LI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "山口研究室",
            },
            {
                nameJa: "ルイヴィル・デリーアン",
                nameEn: "DAREY-ANN LOUISVILLE",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "ペニントン研究室",
            },
        ],
    },
    {
        name: "WEB",
        members: [
            {
                nameJa: "平林晴馬",
                nameEn: "HARUMA HIRABAYASHI",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "矢谷研究室",
            },
            {
                nameJa: "田中祐玖",
                nameEn: "TASUKU TANAKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                nameJa: "席竞帆",
                nameEn: "JINGFAN XI",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                nameJa: "増田凌",
                nameEn: "RYO MASUDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士2年",
                lab: "染谷研究室",
            },
            {
                nameJa: "吉田翼",
                nameEn: "TSUBASA YOSHIDA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "王文鶴",
                nameEn: "WENHE WANG",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "山川研究室",
            },
            {
                nameJa: "金田昌也",
                nameEn: "MASAYA KANEDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士2年",
                lab: "大矢研究室",
            },
        ],
    },
    {
        name: "GALLERY",
        members: [
            {
                nameJa: "小西優多郎",
                nameEn: "YUTARO KONISHI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                nameJa: "機田悠希",
                nameEn: "YUKI KIDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "本間研究室",
            },
            {
                nameJa: "福田晴紀",
                nameEn: "HARUKI FUKUDA",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "増子優輝",
                nameEn: "YUKI MASUKO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "上條研究室",
            },
            {
                nameJa: "有川由祐",
                nameEn: "YUSUKE ARIKAWA",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "足立信基",
                nameEn: "NOBUKI ADACHI",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "本間研究室",
            },
            {
                nameJa: "新井翔太",
                nameEn: "SHOTA ARAI",
                affiliationJa: "東京大学 工学部機械情報工学科",
                grade: "学部4年",
                lab: "國吉・中嶋研究室",
            },
            {
                nameJa: "井上国太郎",
                nameEn: "KUNITARO INOUE",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "渡邊研究室",
            },
            {
                nameJa: "ウォンマタイ",
                nameEn: "HWANG MATTHEW",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "大石研究室",
            },
            {
                nameJa: "西岡春菜",
                nameEn: "HARUNA NISHIOKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "石崎研究室",
            },
            {
                nameJa: "徐錦芸",
                nameEn: "XU JINYI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "蜂須賀研究室",
            },
            {
                nameJa: "梅田悠哉",
                nameEn: "YUYA UMEDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "矢谷研究室",
            },
            {
                nameJa: "鈴木健",
                nameEn: "TAKERU SUZUKI",
                affiliationJa: "東京大学大学院 情報学環教育部",
                grade: "教育部2年",
                lab: "",
            },
            {
                nameJa: "金澤政宜",
                nameEn: "MASANOBU KANAZAWA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                nameJa: "柿川穂香",
                nameEn: "HONOKA KAKIGAWA",
                affiliationJa: "フェリス女学院大学 音楽学部",
                grade: "学部4年",
                lab: "",
            },
        ],
    },
    {
        name: "PUBLIC RELATIONS",
        members: [
            {
                nameJa: "都築あい",
                nameEn: "AI TSUZUKI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                nameJa: "高橋一成",
                nameEn: "ISSEY TAKAHASHI",
                affiliationJa: "早稲田大学大学院 基幹理工学研究科",
                grade: "修士1年",
                lab: "橋田研究室",
            },
            {
                nameJa: "常盤優菜",
                nameEn: "YUNA TOKIWA",
                affiliationJa: "フェリス女学院大学大学院 音楽研究科",
                grade: "修士2年",
                lab: "中西研究室",
            },
            {
                nameJa: "森田匠",
                nameEn: "TAKUMI MORITA",
                affiliationJa: "東京大学 文科三類",
                grade: "学部2年",
                lab: "",
            },
            {
                nameJa: "増澤茉利子",
                nameEn: "MARIKO MASUZAWA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "ペニントン研究室",
            },
            {
                nameJa: "カーアーネスト・航太",
                nameEn: "EARNEST KOTA CARR",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "国吉研究室",
            },
            {
                nameJa: "十河翔",
                nameEn: "SHO SOGO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "田中研究室",
            },
        ],
    },
    {
        name: "ARCHIVE",
        members: [
            {
                nameJa: "大平麻以",
                nameEn: "MAI OHIRA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                nameJa: "加藤遼真",
                nameEn: "RYOMA KATO",
                affiliationJa: "早稲田大学大学院 基幹理工学研究科",
                grade: "修士1年",
                lab: "橋田研究室",
            },
            {
                nameJa: "澤田智佳",
                nameEn: "TOMOKA SAWADA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "岡田・小島研究室",
            },
            {
                nameJa: "坪山倫",
                nameEn: "RIN TSUBOYAMA",
                affiliationJa: "東京大学 文学部社会学専修",
                grade: "学部4年",
                lab: "出口剛司ゼミ",
            },
            {
                nameJa: "あんどう・やすし",
                nameEn: "YASUSHI ANDO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "博士2年",
                lab: "横山研究室",
            },
            {
                nameJa: "石川虎之介",
                nameEn: "TORANOSUKE ISHIKAWA",
                affiliationJa: "早稲田大学大学院 基幹理工学研究科",
                grade: "修士1年",
                lab: "橋田研究室",
            },
        ],
    },
    {
        name: "PROOFREADING",
        members: [
            {
                nameJa: "中野博貴",
                nameEn: "HIROKI NAKANO",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "矢谷研究室",
            },
            {
                nameJa: "花岡桃可",
                nameEn: "MOMOKA HANAOKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "沼田研究室",
            },
            {
                nameJa: "大河内洋平",
                nameEn: "YOHEI OKOCHI",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・谷川・鳴海研究室",
            },
            {
                nameJa: "中根葵",
                nameEn: "AOI NAKANE",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "岡田・小島研究室",
            },
            {
                nameJa: "シェーン・ジョー",
                nameEn: "Shen Zhou",
                affiliationJa: "東京大学 文学部美学芸術学",
                grade: "",
                lab: "",
            },
        ],
    },
    {
        name: "GUEST",
        members: [
            {
                nameJa: "八木新平",
                nameEn: "SHINPEI YAGI",
                affiliationJa: "東京藝術大学 美術学部",
                grade: "4年",
                lab: "",
            },
            {
                nameJa: "桶家武尊",
                nameEn: "TAKERU OKEIE",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                nameJa: "池田翔",
                nameEn: "TSUBASA IKEDA",
                affiliationJa: "東京藝術大学大学院 音楽研究科",
                grade: "修士2年",
                lab: "",
            },
            {
                nameJa: "森達也",
                nameEn: "TATSUYA MORI",
                affiliationJa: "株式会社ARAYA",
                grade: "",
                lab: "",
            },
            {
                nameJa: "谷凪彩",
                nameEn: "NAGISA TANI",
                affiliationJa: "多摩美術大学 美術学部",
                grade: "3年",
                lab: "",
            },
            {
                nameJa: "永田莉紗",
                nemeEn: "RISA NAGATA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "筧研究室",
            },
            {
                nameJa: "あん",
                nameEn: "ANNE",
                affiliationJa: "Peace Activist",
                grade: "",
                lab: "",
            },
            {
                nameJa: "石田颯人",
                nameEn: "ISHIDA",
                affiliationJa: "サウンドプログラマー",
                grade: "",
                lab: "",
            },
            {
                nameJa: "カモクセイ",
                nameEn: "MUXI HUA",
                affiliationJa: "情報理工学系研究科 創造情報専攻",
                grade: "修士2年",
                lab: "五十嵐研究室",
            },
            {
                nameJa: "sion",
                nameEn: "SION",
                affiliationJa: "コデザインリサーチャー / XRアーティスト",
                grade: "",
                lab: "",
            },
            {
                nameJa: "白井崇陽",
                nameEn: "SHIRAI",
                affiliationJa: "バイオリニスト",
                grade: "",
                lab: "",
            },
            {
                nameJa: "中山蒼玄",
                nameEn: "NAKAYAMA SOGEN",
                affiliationJa: "九州大学大学院 芸術工学府",
                grade: "",
                lab: "",
            },
            {
                nameJa: "南部隆一",
                nameEn: "NAMBU RYUICHI",
                affiliationJa: "ACTANT代表 / ACTANT FOREST共同主宰",
                grade: "",
                lab: "",
            },
            {
                nameJa: "真しろ",
                nameEn: "MASHIRO",
                affiliationJa: "立教大学大学院生",
                grade: "",
                lab: "",
            },
            {
                nameJa: "胡欣雨",
                nameEn: "XINYU HU",
                affiliationJa: "情報理工学系研究科 創造情報専攻",
                grade: "修士2年",
                lab: "五十嵐研究室",
            },
            {
                nameJa: "中村雅人",
                nameEn: "MASATO NAKAMURA",
                affiliationJa: "俳優・監督",
                grade: "",
                lab: "",
            },
            {
                nameJa: "姚思妤",
                nameEn: "SIYU YAO",
                affiliationJa: "慶應義塾大学大学院 メディアデザイン研究科",
                grade: "",
                lab: "",
            },
            {
                nameJa: "何婧",
                nameEn: "KASEI",
                affiliationJa: "華東師範大学大学院 デザイン学院",
                grade: "修士1年",
                lab: "",
            },
            {
                nameJa: "岡空来",
                nameEn: "SORA OKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                nameJa: "カイカセイ",
                nameEn: "KAI",
                affiliationJa: "小学生",
                grade: "",
                lab: "",
            },
            {
                nameJa: "金澤政宜",
                nameEn: "",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                nameJa: "森田崇文",
                nameEn: "",
                affiliationJa: "東京大学大学院",
                grade: "助教",
                lab: "情報学環",
            },
            {
                nameJa: "吳冠儒",
                nameEn: "",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "博士課程2年",
                lab: "筧研究室",
            },
            {
                nameJa: "岩瀬英治",
                nameEn: "",
                affiliationJa: "早稲田大学 理工学術院",
                grade: "教授",
                lab: "岩瀬研究室",
            },
        ],
    },
    {
        name: "FACULTY ADVISER",
        members: [
            {
                nameJa: "苗村健",
                nameEn: "TAKESHI NAEMURA",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                nameJa: "筧康明",
                nameEn: "YASUAKI KAKEHI",
                affiliationJa: "東京大学大学院",
                grade: "教授",
                lab: "情報学環",
            },
            {
                nameJa: "渡邉英徳",
                nameEn: "HIDENORI WATANAVE",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                nameJa: "曽根光揮",
                nameEn: "KOKI SONE",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                nameJa: "武井祥平",
                nameEn: "SHOHEI TAKEI",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                nameJa: "倉本大資",
                nameEn: "DAISUKE KURAMOTO",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                nameJa: "増田悠紀子",
                nameEn: "YUKIKO MASUDA",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
        ],
    },
] as const;
