export const teamList = [
    {
        name: "PROJECT DIRCTOR",
        members: [
            {
                name: "真田将太朗",
                nameLang: "ja",
                nameEn: "SHOTARO SANADA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                name: "石津悠人",
                nameLang: "ja",
                nameEn: "YUTO ISHIZU",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "中田裕紀",
                nameLang: "ja",
                nameEn: "YUKI NAKATA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                name: "南田桂吾",
                nameLang: "ja",
                nameEn: "KEIGO MINAMIDA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "暦本研究室",
            },
        ],
    },
    {
        name: "PROJECT MANAGER",
        members: [
            {
                name: "仲村友杜",
                nameLang: "ja",
                nameEn: "YUTO NAKAMURA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "暦本研究室",
            },
            {
                name: "星杏優菜",
                nameLang: "ja",
                nameEn: "AYUNA HOSHI",
                affiliationJa: "フェリス女学院大学大学院 音楽研究科",
                grade: "修士2年",
                lab: "中西研究室",
            },
            {
                name: "莫子敏",
                nameLang: "zh-Hans",
                nameEn: "ZIMIN MO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "藤本研究室",
            },
        ],
    },
    {
        name: "BRANDING",
        members: [
            {
                name: "横井総太朗",
                nameLang: "ja",
                nameEn: "SOTARO YOKOI",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "宮道彩乃",
                nameLang: "ja",
                nameEn: "AYANO MIYAMICHI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "岡田・小島研究室",
            },
        ],
    },
    {
        name: "ACCOUNTANT",
        members: [
            {
                name: "友利未夢",
                nameLang: "ja",
                nameEn: "MIYU TOMORI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "山内研究室",
            },
            {
                name: "牛島百合子",
                nameLang: "ja",
                nameEn: "YURIKO USHIJIMA",
                affiliationJa: "東京大学大学院 情報学環教育部",
                grade: "教育部 1年",
                lab: "渡邉研究室",
            },
        ],
    },
    {
        name: "DESIGN",
        members: [
            {
                name: "李伊婧",
                nameLang: "zh-Hans",
                nameEn: "ISEI LI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "李婧",
                nameLang: "zh-Hans",
                nameEn: "JING LI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "渡邊研究室",
            },
            {
                name: "余楚韵",
                nameLang: "zh-Hans",
                nameEn: "CHUYUN YU",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "渡邊研究室",
            },
            {
                name: "李嘉懿",
                nameLang: "zh-Hans",
                nameEn: "ANRY LI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "山口研究室",
            },
            {
                name: "ルイヴィル・デリーアン",
                nameLang: "ja",
                nameEn: "DAREY-ANN LOUISVILLE",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "ペニントン研究室",
            },
        ],
    },
    {
        name: "WEB",
        members: [
            {
                name: "平林晴馬",
                nameLang: "ja",
                nameEn: "HARUMA HIRABAYASHI",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "矢谷研究室",
            },
            {
                name: "田中祐玖",
                nameLang: "ja",
                nameEn: "TASUKU TANAKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                name: "席竞帆",
                nameLang: "zh-Hans",
                nameEn: "JINGFAN XI",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                name: "増田凌",
                nameLang: "ja",
                nameEn: "RYO MASUDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士2年",
                lab: "染谷研究室",
            },
            {
                name: "吉田翼",
                nameLang: "ja",
                nameEn: "TSUBASA YOSHIDA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "王文鶴",
                nameLang: "ja",
                nameEn: "WENHE WANG",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "山川研究室",
            },
            {
                name: "金田昌也",
                nameLang: "ja",
                nameEn: "MASAYA KANEDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士2年",
                lab: "大矢研究室",
            },
        ],
    },
    {
        name: "GALLERY",
        members: [
            {
                name: "小西優多郎",
                nameLang: "ja",
                nameEn: "YUTARO KONISHI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                name: "機田悠希",
                nameLang: "ja",
                nameEn: "YUKI KIDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "本間研究室",
            },
            {
                name: "福田晴紀",
                nameLang: "ja",
                nameEn: "HARUKI FUKUDA",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "増子優輝",
                nameLang: "ja",
                nameEn: "YUKI MASUKO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "上條研究室",
            },
            {
                name: "有川由祐",
                nameLang: "ja",
                nameEn: "YUSUKE ARIKAWA",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "足立信基",
                nameLang: "ja",
                nameEn: "NOBUKI ADACHI",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "本間研究室",
            },
            {
                name: "新井翔太",
                nameLang: "ja",
                nameEn: "SHOTA ARAI",
                affiliationJa: "東京大学 工学部機械情報工学科",
                grade: "学部4年",
                lab: "國吉・中嶋研究室",
            },
            {
                name: "井上国太郎",
                nameLang: "ja",
                nameEn: "KUNITARO INOUE",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "渡邊研究室",
            },
            {
                name: "ウォンマタイ",
                nameLang: "ja",
                nameEn: "HWANG MATTHEW",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "大石研究室",
            },
            {
                name: "西岡春菜",
                nameLang: "ja",
                nameEn: "HARUNA NISHIOKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "石崎研究室",
            },
            {
                name: "徐錦芸",
                nameLang: "ja",
                nameEn: "XU JINYI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "蜂須賀研究室",
            },
            {
                name: "梅田悠哉",
                nameLang: "ja",
                nameEn: "YUYA UMEDA",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "矢谷研究室",
            },
            {
                name: "鈴木健",
                nameLang: "ja",
                nameEn: "TAKERU SUZUKI",
                affiliationJa: "東京大学大学院 情報学環教育部",
                grade: "教育部2年",
                lab: "",
            },
            {
                name: "金澤政宜",
                nameLang: "ja",
                nameEn: "MASANOBU KANAZAWA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                name: "柿川穂香",
                nameLang: "ja",
                nameEn: "HONOKA KAKIGAWA",
                affiliationJa: "フェリス女学院大学 音楽学部",
                grade: "学部4年",
                lab: "",
            },
        ],
    },
    {
        name: "PUBLIC RELATIONS",
        members: [
            {
                name: "都築あい",
                nameLang: "ja",
                nameEn: "AI TSUZUKI",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "苗村研究室",
            },
            {
                name: "高橋一成",
                nameLang: "ja",
                nameEn: "ISSEY TAKAHASHI",
                affiliationJa: "早稲田大学大学院 基幹理工学研究科",
                grade: "修士1年",
                lab: "橋田研究室",
            },
            {
                name: "常盤優菜",
                nameLang: "ja",
                nameEn: "YUNA TOKIWA",
                affiliationJa: "フェリス女学院大学大学院 音楽研究科",
                grade: "修士2年",
                lab: "中西研究室",
            },
            {
                name: "森田匠",
                nameLang: "ja",
                nameEn: "TAKUMI MORITA",
                affiliationJa: "東京大学 文科三類",
                grade: "学部2年",
                lab: "",
            },
            {
                name: "増澤茉利子",
                nameLang: "ja",
                nameEn: "MARIKO MASUZAWA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "ペニントン研究室",
            },
            {
                name: "カーアーネスト・航太",
                nameLang: "ja",
                nameEn: "EARNEST KOTA CARR",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "国吉研究室",
            },
            {
                name: "十河翔",
                nameLang: "ja",
                nameEn: "SHO SOGO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "田中研究室",
            },
        ],
    },
    {
        name: "ARCHIVE",
        members: [
            {
                name: "大平麻以",
                nameLang: "ja",
                nameEn: "MAI OHIRA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "筧研究室",
            },
            {
                name: "加藤遼真",
                nameLang: "ja",
                nameEn: "RYOMA KATO",
                affiliationJa: "早稲田大学大学院 基幹理工学研究科",
                grade: "修士1年",
                lab: "橋田研究室",
            },
            {
                name: "澤田智佳",
                nameLang: "ja",
                nameEn: "TOMOKA SAWADA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "岡田・小島研究室",
            },
            {
                name: "坪山倫",
                nameLang: "ja",
                nameEn: "RIN TSUBOYAMA",
                affiliationJa: "東京大学 文学部社会学専修",
                grade: "学部4年",
                lab: "出口剛司ゼミ",
            },
            {
                name: "あんどうやすし",
                nameLang: "ja",
                nameEn: "YASUSHI ANDO",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "博士2年",
                lab: "横山研究室",
            },
            {
                name: "石川虎之介",
                nameLang: "ja",
                nameEn: "TORANOSUKE ISHIKAWA",
                affiliationJa: "早稲田大学大学院 基幹理工学研究科",
                grade: "修士1年",
                lab: "橋田研究室",
            },
        ],
    },
    {
        name: "PROOFREADING",
        members: [
            {
                name: "中野博貴",
                nameLang: "ja",
                nameEn: "HIROKI NAKANO",
                affiliationJa: "東京大学大学院 工学系研究科",
                grade: "修士1年",
                lab: "矢谷研究室",
            },
            {
                name: "花岡桃可",
                nameLang: "ja",
                nameEn: "MOMOKA HANAOKA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士1年",
                lab: "沼田研究室",
            },
            {
                name: "大河内洋平",
                nameLang: "ja",
                nameEn: "YOHEI OKOCHI",
                affiliationJa: "東京大学大学院 情報理工学系研究科",
                grade: "修士1年",
                lab: "葛岡・鳴海研究室",
            },
            {
                name: "中根葵",
                nameLang: "ja",
                nameEn: "AOI NAKANE",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "岡田・小島研究室",
            },
            {
                name: "シェーン・ジョー",
                nameLang: "ja",
                nameEn: "Shen Zhou",
                affiliationJa: "東京大学 文学部美学芸術学",
                grade: "",
                lab: "",
            },
        ],
    },
    {
        name: "GUEST",
        members: [
            {
                name: "八木新平",
                nameLang: "ja",
                nameEn: "SHINPEI YAGI",
                affiliationJa: "東京藝術大学 美術学部",
                grade: "4年",
                lab: "",
            },
            {
                name: "桶家武尊",
                nameLang: "ja",
                nameEn: "TAKERU OKEIE",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "池田翔",
                nameLang: "ja",
                nameEn: "TSUBASA IKEDA",
                affiliationJa: "東京藝術大学大学院 音楽研究科",
                grade: "修士2年",
                lab: "",
            },
            {
                name: "森達也",
                nameLang: "ja",
                nameEn: "TATSUYA MORI",
                affiliationJa: "株式会社ARAYA",
                grade: "",
                lab: "",
            },
            {
                name: "谷凪彩",
                nameLang: "ja",
                nameEn: "NAGISA TANI",
                affiliationJa: "多摩美術大学 美術学部",
                grade: "3年",
                lab: "",
            },
            {
                name: "永田莉紗",
                nameLang: "ja",
                nemeEn: "RISA NAGATA",
                affiliationJa: "東京大学大学院 学際情報学府",
                grade: "修士2年",
                lab: "筧研究室",
            },
            {
                name: "あん",
                nameLang: "ja",
                nameEn: "ANNE",
                affiliationJa: "Peace Activist",
                grade: "",
                lab: "",
            },
        ],
    },
    {
        name: "FACULTY ADVISER",
        members: [
            {
                name: "苗村健",
                nameLang: "ja",
                nameEn: "TAKESHI NAEMURA",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "筧康明",
                nameLang: "ja",
                nameEn: "YASUAKI KAKEHI",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "渡邉英徳",
                nameLang: "ja",
                nameEn: "HIDENORI WATANAVE",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "曽根光揮",
                nameLang: "ja",
                nameEn: "KOKI SONE",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "武井祥平",
                nameLang: "ja",
                nameEn: "SHOHEI TAKEI",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "倉本大資",
                nameLang: "ja",
                nameEn: "DAISUKE KURAMOTO",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
            {
                name: "増田悠紀子",
                nameLang: "ja",
                nameEn: "YUKIKO MASUDA",
                affiliationJa: "",
                grade: "",
                lab: "",
            },
        ],
    },
] as const;
