import { Place } from "@/models/place";

export type WorkData = {
    title: string;
    member: string[];
    place: Place;
    description: {
        ja: string;
        en: string;
    };
    imagePath: string;
};

export const workList = [
    {
        title: "帝大下水",
        member: ["あんどうやすし", "十河翔"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: `春は赤門に桜が舞い、夏は三四郎池に蝉時雨が降る。秋は銀杏並木が黄金色に染まり、冬は……まぁなんかさみしい。そんな東大本郷キャンパスにはあなたの知らない裏がある。「帝大下水」は目に映るキャンパスの姿を大きく変える。刮目。`,
            en: `In spring, cherry blossoms flutter around the iconic Red Gate, while in summer, the sound of cicadas rains down over Sanshiro Pond. Autumn brings a golden glow to the ginkgo tree-lined paths, but winter... well, it's a bit lonely. Yet, there’s a hidden side to the University of Tokyo’s Hongo Campus that you may not know: "Teidai Sewers" could transform the campus as you see it. Keep your eyes peeled.`,
        },
        imagePath: "/works/manhole-bw.png",
    },
    {
        title: "zip or",
        member: ["増田凌", "大平麻以", "加藤遼真", "石川虎之介", "永田莉紗", "金田昌也"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: `ジッパーは「金属やプラスチック製の角張った構造が互いに噛み合い、直線を形成する」という強い人工物らしさをもっている。そんなジッパーを用いながら自然がもつ有機的な形を表現することはできるのだろうか。
            本作品では所望の曲線に沿うようコンピュテーショナルに設計・製造されたジッパーによって形作られた立体を提示する。ジッパーは布を支える骨格となり、その開閉によって立体の形を変化させる。
            服を着る。
            鞄にものをしまう。
            日常に埋もれていた｢ジッパーを開閉する｣という行為に新たな意味を見出すことができるかもしれない。`,
            en: `
Zippers, with their distinct artificial quality—where metal or plastic teeth interlock to form a straight line—are emblematic of human-made design. But can these rigid structures be used to express organic, natural forms? This piece showcases a computationally designed zipper, crafted to follow desired curves, forming a three-dimensional object. The zipper acts as a skeleton for fabric, transforming the shape as it opens and closes. Everyday actions like wearing clothes or zipping a bag may take on new meaning through this exploration of the zipper’s potential.`,
        },
        imagePath: "/works/zip-bw.png",
    },
    {
        title: "Prismatic Diary",
        member: ["横井総太朗", "小西優多郎", "李伊婧", "平林晴馬", "吉田翼", "都築あい"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: `本作品では、日記の執筆中に生成AIによる複数の解釈を展開し、少し違う「私」へ出会う体験を実現した。出来事の異なった解釈の可能性に気付いた瞬間、あなたの世界の見え方は虹色に変わっていくだろう。`,
            en: `In this work, multiple interpretations generated by AI unfold as you write in a diary, allowing you to encounter a slightly different version of "yourself." The moment you realize the potential for various interpretations of events, your perception of the world will begin to change, as if viewed through a rainbow-colored lens.`,
        },
        imagePath: "/works/prismatic-bw.png",
    },
    {
        title: "裏地図",
        member: ["井上国太郎", "田中祐玖", "機田悠希", "花岡桃可", "鈴木健"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: "裏地図は、「三幕物」として構成される。写真とドローイングに支えられた裏地図は、一連の流れを伴う経験である。裏地図は、旗や横断幕を利用したあらゆる運動へのオマージュである。未来の「纏える」地図に向かって、裏地図は歩き始める。布という平面に描き込まれた地図は、裁断/縫合によって将来的には立体的な服に加工され、日常に溶け込む。",
            en: `The Reverse Map is structured as a "three-act" experience, supported by photos and drawings. It is a tribute to various movements that use flags and banners. As it moves toward a future where maps can be "worn," the reverse map begins to walk. Maps drawn on the flat surface of fabric are cut and sewn into three-dimensional clothing, eventually blending into daily life.`,
        },

        imagePath: "/works/backmap-bw.png",
    },
    {
        title: "空間新聞",
        member: ["森田匠", "高橋一成"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: "本作品は、情報を人が歩いて運んでくる世界の新聞である。そのため、情報の発信源が遠いほどこの新聞に載る情報は古いものとなっていく。鑑賞者は、今まさに自分が立っている身体空間の広がりを感じることができる。メディアは、これまで遠い地域の情報を集約・分配し、距離的な隔たりを除去することで、社会の一体感や国民意識の醸成に寄与してきた。本作品では「遅いメディア」を通じて、「国民国家」や「グローバル化」が前提としてきた情報の同時性の解体に挑戦している。",
            en: `This work represents a newspaper from a world where information is physically carried by people. The farther the source, the older the news becomes. Viewers experience the spatial connection of their current location. Traditional media has dissolved geographical distances, fostering national and global unity. By embracing a "slow media" approach, this piece challenges the assumption of simultaneous information flow, which has underpinned the concepts of the nation-state and globalization.`,
        },

        imagePath: "/works/newspaper-bw.png",
    },
    {
        title: "The Tower",
        member: ["友利未夢", "國仲杏", "常盤優菜", "増澤茉利子", "谷なぎさ"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: "本作品は「文化的同化」へのアンチテーゼを表現する、クレイアニメーションである。ねんどで作られた個性豊かなキャラクターたちは、1,440枚の静止画を繋ぎ合わせることで命が吹き込まれ、世界を表現していく。",
            en: `This work is a clay animation that expresses an antithesis to "cultural assimilation." The unique characters, made from clay, come to life as 1,440 still images are connected to create motion and depict their world. Through this medium, the piece conveys individuality and resistance to the homogenization of culture.`,
        },

        imagePath: "/works/tower-bw.png",
    },
    {
        title: "Tシャツのトポロジー最適化",
        member: ["金田昌也", "福田晴紀", "増田凌", "永田莉紗"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: "トポロジー最適化とは与えられた設計空間と機能要請のなかで最小限の材料配置を決定する設計手法のことで、工業部品の軽量化や性能向上に利用されている。では、洋服をトポロジー最適化してみたらどうなるだろうか。",
            en: `Topology optimization is a design method used to determine the minimal material arrangement within a given design space to meet functional requirements. It's commonly applied in industries for lightweighting and improving the performance of mechanical components. But what would happen if we applied topology optimization to clothing? Could we minimize the material used in clothing design while maintaining its function and aesthetics, possibly revolutionizing the way we think about fashion and material efficiency?`,
        },

        imagePath: "/works/tshirt-bw.png",
    },
    {
        title: "Area of Landscape",
        member: ["真田将太朗", "森達也", "八木新平", "桶家武尊", "池田翔", "仲村友杜"],
        place: "情報学環オープンスタジオ",
        description: {
            ja: "本作は、絵画の形態を決定する要素として鑑賞者の姿を積極的に取り入れている。絵画空間へと迎えられ、完成へと向かう絵画の一部となる体験を通して、差異と調和に満ちた「新しい風景」の見方を示す。キャンバスに色が置かれるたび、絵画のなかで要素どうしの関係性が生成と消滅を繰り返す。自らが抽象風景を作る一つの要素となったとき、世界の見つめ方はどのように変わるだろうか。",
            en: `This work actively incorporates the viewer’s presence as a key element in shaping the form of the painting. Invited into the painting’s space, viewers become part of the evolving artwork, contributing to its completion. Each stroke of color alters the relationships between elements, which continually appear and disappear. The experience of becoming a component of this abstract landscape offers a new perspective on difference and harmony. How does one’s perception of the world shift when they themselves become a part of the abstract scene they observe?`,
        },
        imagePath: "/works/landscape-bw.png",
    },
    {
        title: "帝大下水",
        member: ["あんどうやすし", "十河翔"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: `春は赤門に桜が舞い、夏は三四郎池に蝉時雨が降る。秋は銀杏並木が黄金色に染まり、冬は……まぁなんかさみしい。そんな東大本郷キャンパスにはあなたの知らない裏がある。「帝大下水」は目に映るキャンパスの姿を大きく変える。刮目。`,
            en: `In spring, cherry blossoms flutter around the iconic Red Gate, while in summer, the sound of cicadas rains down over Sanshiro Pond. Autumn brings a golden glow to the ginkgo tree-lined paths, but winter... well, it's a bit lonely. Yet, there’s a hidden side to the University of Tokyo’s Hongo Campus that you may not know: "Teidai Sewers" could transform the campus as you see it. Keep your eyes peeled.`,
        },
        imagePath: "/works/manhole-bw.png",
    },
    {
        title: "zip or",
        member: ["増田凌", "大平麻以", "加藤遼真", "石川虎之介", "永田莉紗", "金田昌也"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: `ジッパーは「金属やプラスチック製の角張った構造が互いに噛み合い、直線を形成する」という強い人工物らしさをもっている。そんなジッパーを用いながら自然がもつ有機的な形を表現することはできるのだろうか。
            本作品では所望の曲線に沿うようコンピュテーショナルに設計・製造されたジッパーによって形作られた立体を提示する。ジッパーは布を支える骨格となり、その開閉によって立体の形を変化させる。
            服を着る。
            鞄にものをしまう。
            日常に埋もれていた｢ジッパーを開閉する｣という行為に新たな意味を見出すことができるかもしれない。`,
            en: `
Zippers, with their distinct artificial quality—where metal or plastic teeth interlock to form a straight line—are emblematic of human-made design. But can these rigid structures be used to express organic, natural forms? This piece showcases a computationally designed zipper, crafted to follow desired curves, forming a three-dimensional object. The zipper acts as a skeleton for fabric, transforming the shape as it opens and closes. Everyday actions like wearing clothes or zipping a bag may take on new meaning through this exploration of the zipper’s potential.`,
        },
        imagePath: "/works/zip-bw.png",
    },
    {
        title: "Prismatic Diary",
        member: ["横井総太朗", "小西優多郎", "李伊婧", "平林晴馬", "吉田翼", "都築あい"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: `本作品では、日記の執筆中に生成AIによる複数の解釈を展開し、少し違う「私」へ出会う体験を実現した。出来事の異なった解釈の可能性に気付いた瞬間、あなたの世界の見え方は虹色に変わっていくだろう。`,
            en: `In this work, multiple interpretations generated by AI unfold as you write in a diary, allowing you to encounter a slightly different version of "yourself." The moment you realize the potential for various interpretations of events, your perception of the world will begin to change, as if viewed through a rainbow-colored lens.`,
        },
        imagePath: "/works/prismatic-bw.png",
    },
    {
        title: "裏地図",
        member: ["井上国太郎", "田中祐玖", "機田悠希", "花岡桃可", "鈴木健"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: "裏地図は、「三幕物」として構成される。写真とドローイングに支えられた裏地図は、一連の流れを伴う経験である。裏地図は、旗や横断幕を利用したあらゆる運動へのオマージュである。未来の「纏える」地図に向かって、裏地図は歩き始める。布という平面に描き込まれた地図は、裁断/縫合によって将来的には立体的な服に加工され、日常に溶け込む。",
            en: `The Reverse Map is structured as a "three-act" experience, supported by photos and drawings. It is a tribute to various movements that use flags and banners. As it moves toward a future where maps can be "worn," the reverse map begins to walk. Maps drawn on the flat surface of fabric are cut and sewn into three-dimensional clothing, eventually blending into daily life.`,
        },

        imagePath: "/works/backmap-bw.png",
    },
    {
        title: "空間新聞",
        member: ["森田匠", "高橋一成"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: "本作品は、情報を人が歩いて運んでくる世界の新聞である。そのため、情報の発信源が遠いほどこの新聞に載る情報は古いものとなっていく。鑑賞者は、今まさに自分が立っている身体空間の広がりを感じることができる。メディアは、これまで遠い地域の情報を集約・分配し、距離的な隔たりを除去することで、社会の一体感や国民意識の醸成に寄与してきた。本作品では「遅いメディア」を通じて、「国民国家」や「グローバル化」が前提としてきた情報の同時性の解体に挑戦している。",
            en: `This work represents a newspaper from a world where information is physically carried by people. The farther the source, the older the news becomes. Viewers experience the spatial connection of their current location. Traditional media has dissolved geographical distances, fostering national and global unity. By embracing a "slow media" approach, this piece challenges the assumption of simultaneous information flow, which has underpinned the concepts of the nation-state and globalization.`,
        },

        imagePath: "/works/newspaper-bw.png",
    },
    {
        title: "The Tower",
        member: ["友利未夢", "國仲杏", "常盤優菜", "増澤茉利子", "谷なぎさ"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: "本作品は「文化的同化」へのアンチテーゼを表現する、クレイアニメーションである。ねんどで作られた個性豊かなキャラクターたちは、1,440枚の静止画を繋ぎ合わせることで命が吹き込まれ、世界を表現していく。",
            en: `This work is a clay animation that expresses an antithesis to "cultural assimilation." The unique characters, made from clay, come to life as 1,440 still images are connected to create motion and depict their world. Through this medium, the piece conveys individuality and resistance to the homogenization of culture.`,
        },

        imagePath: "/works/tower-bw.png",
    },
    {
        title: "Tシャツのトポロジー最適化",
        member: ["金田昌也", "福田晴紀", "増田凌", "永田莉紗"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: "トポロジー最適化とは与えられた設計空間と機能要請のなかで最小限の材料配置を決定する設計手法のことで、工業部品の軽量化や性能向上に利用されている。では、洋服をトポロジー最適化してみたらどうなるだろうか。",
            en: `Topology optimization is a design method used to determine the minimal material arrangement within a given design space to meet functional requirements. It's commonly applied in industries for lightweighting and improving the performance of mechanical components. But what would happen if we applied topology optimization to clothing? Could we minimize the material used in clothing design while maintaining its function and aesthetics, possibly revolutionizing the way we think about fashion and material efficiency?`,
        },

        imagePath: "/works/tshirt-bw.png",
    },
    {
        title: "Area of Landscape",
        member: ["真田将太朗", "森達也", "八木新平", "桶家武尊", "池田翔", "仲村友杜"],
        place: "工学部2号館9階・Sky Presentation Room",
        description: {
            ja: "本作は、絵画の形態を決定する要素として鑑賞者の姿を積極的に取り入れている。絵画空間へと迎えられ、完成へと向かう絵画の一部となる体験を通して、差異と調和に満ちた「新しい風景」の見方を示す。キャンバスに色が置かれるたび、絵画のなかで要素どうしの関係性が生成と消滅を繰り返す。自らが抽象風景を作る一つの要素となったとき、世界の見つめ方はどのように変わるだろうか。",
            en: `This work actively incorporates the viewer’s presence as a key element in shaping the form of the painting. Invited into the painting’s space, viewers become part of the evolving artwork, contributing to its completion. Each stroke of color alters the relationships between elements, which continually appear and disappear. The experience of becoming a component of this abstract landscape offers a new perspective on difference and harmony. How does one’s perception of the world shift when they themselves become a part of the abstract scene they observe?`,
        },
        imagePath: "/works/landscape-bw.png",
    },
    {
        title: "帝大下水",
        member: ["あんどうやすし", "十河翔"],
        place: "工学部2号館フォーラム",
        description: {
            ja: `春は赤門に桜が舞い、夏は三四郎池に蝉時雨が降る。秋は銀杏並木が黄金色に染まり、冬は……まぁなんかさみしい。そんな東大本郷キャンパスにはあなたの知らない裏がある。「帝大下水」は目に映るキャンパスの姿を大きく変える。刮目。`,
            en: `In spring, cherry blossoms flutter around the iconic Red Gate, while in summer, the sound of cicadas rains down over Sanshiro Pond. Autumn brings a golden glow to the ginkgo tree-lined paths, but winter... well, it's a bit lonely. Yet, there’s a hidden side to the University of Tokyo’s Hongo Campus that you may not know: "Teidai Sewers" could transform the campus as you see it. Keep your eyes peeled.`,
        },
        imagePath: "/works/manhole-bw.png",
    },
    {
        title: "zip or",
        member: ["増田凌", "大平麻以", "加藤遼真", "石川虎之介", "永田莉紗", "金田昌也"],
        place: "工学部2号館フォーラム",
        description: {
            ja: `ジッパーは「金属やプラスチック製の角張った構造が互いに噛み合い、直線を形成する」という強い人工物らしさをもっている。そんなジッパーを用いながら自然がもつ有機的な形を表現することはできるのだろうか。
            本作品では所望の曲線に沿うようコンピュテーショナルに設計・製造されたジッパーによって形作られた立体を提示する。ジッパーは布を支える骨格となり、その開閉によって立体の形を変化させる。
            服を着る。
            鞄にものをしまう。
            日常に埋もれていた｢ジッパーを開閉する｣という行為に新たな意味を見出すことができるかもしれない。`,
            en: `
Zippers, with their distinct artificial quality—where metal or plastic teeth interlock to form a straight line—are emblematic of human-made design. But can these rigid structures be used to express organic, natural forms? This piece showcases a computationally designed zipper, crafted to follow desired curves, forming a three-dimensional object. The zipper acts as a skeleton for fabric, transforming the shape as it opens and closes. Everyday actions like wearing clothes or zipping a bag may take on new meaning through this exploration of the zipper’s potential.`,
        },
        imagePath: "/works/zip-bw.png",
    },
    {
        title: "Prismatic Diary",
        member: ["横井総太朗", "小西優多郎", "李伊婧", "平林晴馬", "吉田翼", "都築あい"],
        place: "工学部2号館フォーラム",
        description: {
            ja: `本作品では、日記の執筆中に生成AIによる複数の解釈を展開し、少し違う「私」へ出会う体験を実現した。出来事の異なった解釈の可能性に気付いた瞬間、あなたの世界の見え方は虹色に変わっていくだろう。`,
            en: `In this work, multiple interpretations generated by AI unfold as you write in a diary, allowing you to encounter a slightly different version of "yourself." The moment you realize the potential for various interpretations of events, your perception of the world will begin to change, as if viewed through a rainbow-colored lens.`,
        },
        imagePath: "/works/prismatic-bw.png",
    },
    {
        title: "裏地図",
        member: ["井上国太郎", "田中祐玖", "機田悠希", "花岡桃可", "鈴木健"],
        place: "工学部2号館フォーラム",
        description: {
            ja: "裏地図は、「三幕物」として構成される。写真とドローイングに支えられた裏地図は、一連の流れを伴う経験である。裏地図は、旗や横断幕を利用したあらゆる運動へのオマージュである。未来の「纏える」地図に向かって、裏地図は歩き始める。布という平面に描き込まれた地図は、裁断/縫合によって将来的には立体的な服に加工され、日常に溶け込む。",
            en: `The Reverse Map is structured as a "three-act" experience, supported by photos and drawings. It is a tribute to various movements that use flags and banners. As it moves toward a future where maps can be "worn," the reverse map begins to walk. Maps drawn on the flat surface of fabric are cut and sewn into three-dimensional clothing, eventually blending into daily life.`,
        },

        imagePath: "/works/backmap-bw.png",
    },
    {
        title: "空間新聞",
        member: ["森田匠", "高橋一成"],
        place: "工学部2号館フォーラム",
        description: {
            ja: "本作品は、情報を人が歩いて運んでくる世界の新聞である。そのため、情報の発信源が遠いほどこの新聞に載る情報は古いものとなっていく。鑑賞者は、今まさに自分が立っている身体空間の広がりを感じることができる。メディアは、これまで遠い地域の情報を集約・分配し、距離的な隔たりを除去することで、社会の一体感や国民意識の醸成に寄与してきた。本作品では「遅いメディア」を通じて、「国民国家」や「グローバル化」が前提としてきた情報の同時性の解体に挑戦している。",
            en: `This work represents a newspaper from a world where information is physically carried by people. The farther the source, the older the news becomes. Viewers experience the spatial connection of their current location. Traditional media has dissolved geographical distances, fostering national and global unity. By embracing a "slow media" approach, this piece challenges the assumption of simultaneous information flow, which has underpinned the concepts of the nation-state and globalization.`,
        },

        imagePath: "/works/newspaper-bw.png",
    },
    {
        title: "The Tower",
        member: ["友利 未夢", "國仲 杏", "常盤 優菜", "増澤 茉利子", "谷 なぎさ"],
        place: "工学部2号館フォーラム",
        description: {
            ja: "本作品は「文化的同化」へのアンチテーゼを表現する、クレイアニメーションである。ねんどで作られた個性豊かなキャラクターたちは、1,440枚の静止画を繋ぎ合わせることで命が吹き込まれ、世界を表現していく。",
            en: `This work is a clay animation that expresses an antithesis to "cultural assimilation." The unique characters, made from clay, come to life as 1,440 still images are connected to create motion and depict their world. Through this medium, the piece conveys individuality and resistance to the homogenization of culture.`,
        },

        imagePath: "/works/tower-bw.png",
    },
    {
        title: "Tシャツのトポロジー最適化",
        member: ["金田昌也", "福田晴紀", "増田凌", "永田莉紗"],
        place: "工学部2号館フォーラム",
        description: {
            ja: "トポロジー最適化とは与えられた設計空間と機能要請のなかで最小限の材料配置を決定する設計手法のことで、工業部品の軽量化や性能向上に利用されている。では、洋服をトポロジー最適化してみたらどうなるだろうか。",
            en: `Topology optimization is a design method used to determine the minimal material arrangement within a given design space to meet functional requirements. It's commonly applied in industries for lightweighting and improving the performance of mechanical components. But what would happen if we applied topology optimization to clothing? Could we minimize the material used in clothing design while maintaining its function and aesthetics, possibly revolutionizing the way we think about fashion and material efficiency?`,
        },

        imagePath: "/works/tshirt-bw.png",
    },
    {
        title: "Area of Landscape",
        member: ["真田将太朗", "森達也", "八木新平", "桶家武尊", "池田翔", "仲村友杜"],
        place: "工学部2号館フォーラム",
        description: {
            ja: "本作は、絵画の形態を決定する要素として鑑賞者の姿を積極的に取り入れている。絵画空間へと迎えられ、完成へと向かう絵画の一部となる体験を通して、差異と調和に満ちた「新しい風景」の見方を示す。キャンバスに色が置かれるたび、絵画のなかで要素どうしの関係性が生成と消滅を繰り返す。自らが抽象風景を作る一つの要素となったとき、世界の見つめ方はどのように変わるだろうか。",
            en: `This work actively incorporates the viewer’s presence as a key element in shaping the form of the painting. Invited into the painting’s space, viewers become part of the evolving artwork, contributing to its completion. Each stroke of color alters the relationships between elements, which continually appear and disappear. The experience of becoming a component of this abstract landscape offers a new perspective on difference and harmony. How does one’s perception of the world shift when they themselves become a part of the abstract scene they observe?`,
        },
        imagePath: "/works/landscape-bw.png",
    },
    {
        title: "帝大下水",
        member: ["あんどうやすし", "十河 翔"],
        place: "工学部2号館展示室",
        description: {
            ja: `春は赤門に桜が舞い、夏は三四郎池に蝉時雨が降る。秋は銀杏並木が黄金色に染まり、冬は……まぁなんかさみしい。そんな東大本郷キャンパスにはあなたの知らない裏がある。「帝大下水」は目に映るキャンパスの姿を大きく変える。刮目。`,
            en: `In spring, cherry blossoms flutter around the iconic Red Gate, while in summer, the sound of cicadas rains down over Sanshiro Pond. Autumn brings a golden glow to the ginkgo tree-lined paths, but winter... well, it's a bit lonely. Yet, there’s a hidden side to the University of Tokyo’s Hongo Campus that you may not know: "Teidai Sewers" could transform the campus as you see it. Keep your eyes peeled.`,
        },
        imagePath: "/works/manhole-bw.png",
    },
    {
        title: "zip or",
        member: ["増田凌", "大平麻以", "加藤遼真", "石川虎之介", "永田莉紗", "金田昌也"],
        place: "工学部2号館展示室",
        description: {
            ja: `ジッパーは「金属やプラスチック製の角張った構造が互いに噛み合い、直線を形成する」という強い人工物らしさをもっている。そんなジッパーを用いながら自然がもつ有機的な形を表現することはできるのだろうか。
            本作品では所望の曲線に沿うようコンピュテーショナルに設計・製造されたジッパーによって形作られた立体を提示する。ジッパーは布を支える骨格となり、その開閉によって立体の形を変化させる。
            服を着る。
            鞄にものをしまう。
            日常に埋もれていた｢ジッパーを開閉する｣という行為に新たな意味を見出すことができるかもしれない。`,
            en: `
Zippers, with their distinct artificial quality—where metal or plastic teeth interlock to form a straight line—are emblematic of human-made design. But can these rigid structures be used to express organic, natural forms? This piece showcases a computationally designed zipper, crafted to follow desired curves, forming a three-dimensional object. The zipper acts as a skeleton for fabric, transforming the shape as it opens and closes. Everyday actions like wearing clothes or zipping a bag may take on new meaning through this exploration of the zipper’s potential.`,
        },
        imagePath: "/works/zip-bw.png",
    },
    {
        title: "Prismatic Diary",
        member: ["横井総太朗", "小西優多郎", "李伊婧", "平林晴馬", "吉田翼", "都築あい"],
        place: "工学部2号館展示室",
        description: {
            ja: `本作品では、日記の執筆中に生成AIによる複数の解釈を展開し、少し違う「私」へ出会う体験を実現した。出来事の異なった解釈の可能性に気付いた瞬間、あなたの世界の見え方は虹色に変わっていくだろう。`,
            en: `In this work, multiple interpretations generated by AI unfold as you write in a diary, allowing you to encounter a slightly different version of "yourself." The moment you realize the potential for various interpretations of events, your perception of the world will begin to change, as if viewed through a rainbow-colored lens.`,
        },
        imagePath: "/works/prismatic-bw.png",
    },
    {
        title: "裏地図",
        member: ["井上国太郎", "田中祐玖", "機田悠希", "花岡桃可", "鈴木健"],
        place: "工学部2号館展示室",
        description: {
            ja: "裏地図は、「三幕物」として構成される。写真とドローイングに支えられた裏地図は、一連の流れを伴う経験である。裏地図は、旗や横断幕を利用したあらゆる運動へのオマージュである。未来の「纏える」地図に向かって、裏地図は歩き始める。布という平面に描き込まれた地図は、裁断/縫合によって将来的には立体的な服に加工され、日常に溶け込む。",
            en: `The Reverse Map is structured as a "three-act" experience, supported by photos and drawings. It is a tribute to various movements that use flags and banners. As it moves toward a future where maps can be "worn," the reverse map begins to walk. Maps drawn on the flat surface of fabric are cut and sewn into three-dimensional clothing, eventually blending into daily life.`,
        },

        imagePath: "/works/backmap-bw.png",
    },
    {
        title: "空間新聞",
        member: ["森田匠", "高橋一成"],
        place: "工学部2号館展示室",
        description: {
            ja: "本作品は、情報を人が歩いて運んでくる世界の新聞である。そのため、情報の発信源が遠いほどこの新聞に載る情報は古いものとなっていく。鑑賞者は、今まさに自分が立っている身体空間の広がりを感じることができる。メディアは、これまで遠い地域の情報を集約・分配し、距離的な隔たりを除去することで、社会の一体感や国民意識の醸成に寄与してきた。本作品では「遅いメディア」を通じて、「国民国家」や「グローバル化」が前提としてきた情報の同時性の解体に挑戦している。",
            en: `This work represents a newspaper from a world where information is physically carried by people. The farther the source, the older the news becomes. Viewers experience the spatial connection of their current location. Traditional media has dissolved geographical distances, fostering national and global unity. By embracing a "slow media" approach, this piece challenges the assumption of simultaneous information flow, which has underpinned the concepts of the nation-state and globalization.`,
        },

        imagePath: "/works/newspaper-bw.png",
    },
    {
        title: "The Tower",
        member: ["友利未夢", "國仲杏", "常盤優菜", "増澤茉利子", "谷なぎさ"],
        place: "工学部2号館展示室",
        description: {
            ja: "本作品は「文化的同化」へのアンチテーゼを表現する、クレイアニメーションである。ねんどで作られた個性豊かなキャラクターたちは、1,440枚の静止画を繋ぎ合わせることで命が吹き込まれ、世界を表現していく。",
            en: `This work is a clay animation that expresses an antithesis to "cultural assimilation." The unique characters, made from clay, come to life as 1,440 still images are connected to create motion and depict their world. Through this medium, the piece conveys individuality and resistance to the homogenization of culture.`,
        },

        imagePath: "/works/tower-bw.png",
    },
    {
        title: "Tシャツのトポロジー最適化",
        member: ["金田昌也", "福田晴紀", "増田凌", "永田莉紗"],
        place: "工学部2号館展示室",
        description: {
            ja: "トポロジー最適化とは与えられた設計空間と機能要請のなかで最小限の材料配置を決定する設計手法のことで、工業部品の軽量化や性能向上に利用されている。では、洋服をトポロジー最適化してみたらどうなるだろうか。",
            en: `Topology optimization is a design method used to determine the minimal material arrangement within a given design space to meet functional requirements. It's commonly applied in industries for lightweighting and improving the performance of mechanical components. But what would happen if we applied topology optimization to clothing? Could we minimize the material used in clothing design while maintaining its function and aesthetics, possibly revolutionizing the way we think about fashion and material efficiency?`,
        },

        imagePath: "/works/tshirt-bw.png",
    },
    {
        title: "Area of Landscape",
        member: ["真田将太朗", "森達也", "八木新平", "桶家武尊", "池田翔", "仲村友杜"],
        place: "工学部2号館展示室",
        description: {
            ja: "本作は、絵画の形態を決定する要素として鑑賞者の姿を積極的に取り入れている。絵画空間へと迎えられ、完成へと向かう絵画の一部となる体験を通して、差異と調和に満ちた「新しい風景」の見方を示す。キャンバスに色が置かれるたび、絵画のなかで要素どうしの関係性が生成と消滅を繰り返す。自らが抽象風景を作る一つの要素となったとき、世界の見つめ方はどのように変わるだろうか。",
            en: `This work actively incorporates the viewer’s presence as a key element in shaping the form of the painting. Invited into the painting’s space, viewers become part of the evolving artwork, contributing to its completion. Each stroke of color alters the relationships between elements, which continually appear and disappear. The experience of becoming a component of this abstract landscape offers a new perspective on difference and harmony. How does one’s perception of the world shift when they themselves become a part of the abstract scene they observe?`,
        },
        imagePath: "/works/landscape-bw.png",
    },
] as const satisfies WorkData[];
